include:
  # Generic dev/feature deployments
  - remote: 'https://gitlab.com/digitalsurgeons/gitlab-ci-configs/raw/master/.gitlab-ci.features.yml'
  # Generic front-end build:
  - local: 'https://gitlab.com/digitalsurgeons/gitlab-ci-configs/raw/master/.gitlab-ci.build-frontend.yml'
  # Generic cypress testing:
  - local: 'https://gitlab.com/digitalsurgeons/gitlab-ci-configs/raw/master/.gitlab-ci.cypress.yml'

deploy_prod:
  extends: .deploy
  script:
    - rsync --copy-unsafe-links -rvzcSl --exclude-from '.rsyncignore' ./ $SERVER_DETAILS_PRD:$SERVER_PATH_PRD
  environment:
    name: production
    url: $PRD_DOMAIN
  when: manual
  only:
    - master

deploy_stage:
  extends: .deploy
  script:
    - rsync --copy-unsafe-links -rvzcSl --exclude-from '.rsyncignore' ./ $SERVER_DETAILS_STG:$SERVER_PATH_STG
  environment:
    name: staging
    url: $STG_DOMAIN
  only:
    # Deploy from hotfix and release branches as well as master, so we
    # can test and make modifications on those branches before finishing
    # out a branch. This leads to fewer version bumps and less repo
    # noise.
    - /^(master|hotfix\/|release\/)/
