# Since we run our tests against deployed environments, we have to
# reverse the typical order
stages:
  - build
  - deploy
  - test

# Manually run cypress integration testing
test:
  image: cypress/included:4.0.2
  script:
    - export CYPRESS_BASE_URL=$(cat cypress_env)
    - echo $CYPRESS_BASE_URL
    - cypress run --headless -b chrome
  artifacts:
    paths:
      - cypress/screenshots
      - cypress/videos
    expire_in: 2 mos
  stage: test
  when: manual
  only:
    refs:
      - branches
    variables:
      - $TEST == "true"
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-tests/

