# Build steps for boilerplate frontend
build_frontend:
  image: node:$NODE_VERSION
  script:
    # Update npm to ensure ci command present
    # TODO: This will eventually cause failures if and when npm itself
    # can no longer run on an earlier version of node. As of the time
    # this change was introduced, the latest npm works all the way back
    # to node 6, so we're going to chance it until npm introduces some
    # breaking change.
    - npm -g i npm
    # Install dependencies
    - npm ci
    - npm run prod
  cache:
    key: npm
    paths:
      - node_modules/
  artifacts:
    paths:
      - public_html/dist/
    expire_in: 2 mos
  stage: build
  only:
    refs:
      - branches
    variables:
      - $FRONTEND == "true"
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-frontend-build/
      - $CI_COMMIT_MESSAGE =~ /skip-build/
