# The dev and feature deployments should be entirely generic to any
# project. Only modify if you have things like symlinking upload
# directories or other script actions to worry about Furthermore, if you
# need to modify you can override from the .gitlab-ci.main.yml main file

deploy_dev:
  extends: .deploy
  script:
    - echo $CI_COMMIT_MESSAGE
    - >
      if [[ $RUN_COMPOSER == "true" ]]; then
        curl -O -L https://gitlab.com/digitalsurgeons/gitlab-ci-configs/raw/master/.rsyncignore-vendor
        rsync --copy-unsafe-links -rvzcSl --exclude-from '.rsyncignore-vendor' --delete ./vendor/ $SERVER_DETAILS_DEV:$SERVER_PATH_DEV/vendor/
      fi
    - echo "$DEV_DOTENV" > .env
    - curl -O -L https://gitlab.com/digitalsurgeons/gitlab-ci-configs/raw/master/.rsyncignore
    - rsync --copy-unsafe-links -rvzcSl --exclude-from '.rsyncignore' ./ $SERVER_DETAILS_DEV:$SERVER_PATH_DEV/
  environment:
    name: development
    url: https://$CI_PROJECT_NAME.$DEV_DOMAIN
  only:
    refs:
      - develop
    variables:
      - $DEVELOP == "true"
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-dev-deploy/
      - $CI_COMMIT_MESSAGE =~ /skip-deploy/

deploy_feature:
  extends: .deploy
  script:
    - >
      if [ $RUN_COMPOSER == "true" ] && [ $CI_COMMIT_MESSAGE != *"skip-backend-build"* ]; then
        curl -O -L https://gitlab.com/digitalsurgeons/gitlab-ci-configs/raw/master/.rsyncignore-vendor
        rsync --copy-unsafe-links -rvzcSl --exclude-from '.rsyncignore-vendor' --delete ./ $SERVER_DETAILS_FEATURE:$SERVER_PATH_FEATURE/vendor/
      fi
    - echo "$DEV_DOTENV" > .env
    - curl -O -L https://gitlab.com/digitalsurgeons/gitlab-ci-configs/raw/master/.rsyncignore
    - rsync --copy-unsafe-links -rvzcSl --exclude-from '.rsyncignore' ./ $SERVER_DETAILS_FEATURE:$SERVER_PATH_FEATURE/
  environment:
    name: $CI_COMMIT_REF_NAME
    url: $FEATURE_DOMAIN
    on_stop: teardown_feature
  only:
    refs:
      - /^feature\//
    variables:
      - $FEATURE == "true"
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-feature-deploy/
      - $CI_COMMIT_MESSAGE =~ /skip-deploy/

teardown_feature:
  extends: .deploy
  variables:
    GIT_STRATEGY: none
  script:
    - ssh $SERVER_DETAILS_DEV rm -rf $SERVER_PATH_FEATURE/
  environment:
    name: $CI_COMMIT_REF_NAME
    action: stop
  when: manual
  only:
    refs:
      - /^feature\//
    variables:
      - $FEATURE == "true"
