# Build steps for composer based backends (laravel, craft 3)
build_backend:
  image: composer:1.9
  script:
    - composer install --prefer-dist --no-dev --no-interaction --no-progress --optimize-autoloader --ignore-platform-reqs
  cache:
    key: composer
    paths:
      - vendor/
  artifacts:
    paths:
      - vendor/
    expire_in: 2 mos
  stage: build
  only:
    refs:
      - branches
    variables:
      - $RUN_COMPOSER == "true"
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-backend-build/
      - $CI_COMMIT_MESSAGE =~ /skip-build/
